# This file was generated by liblab | https://liblab.com/

from nyt_archives import NytArchives, Environment

sdk = NytArchives(api_key="", base_url=Environment.DEFAULT.value)

result = sdk.archive.get_by_year_month_json(year=2018, month=9)

print(result)
